# baseurl: /tufte-jekyll
title: Vesperale
subtitle: Laudate Dominum
author: Societas Sancti Gregorii Magni
simple_search: http://google.com/search
description: A site for publishing Gregorian notations for Vespers gatherings of the Society of Saint Gregory the Great
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /vesperas/:year/:title
timezone: Europe/Helsinki
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
